[build]
  base = "/"
  command = "make api-build"
  functions = "build"
  publish = "build"

[build.environment]
  GO_VERSION = "1.19.6"
  GO_IMPORT_PATH = "https://github.com/nshumoogum/fantasy-football"
  GOBIN = "/opt/build/repo/build"
